"""initial

Revision ID: 98da1ca4ca81
Revises: 
Create Date: 2026-04-23 00:01:59.073506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98da1ca4ca81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kayit_bekleyen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('sektor', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('link_gonderildi', sa.DateTime(), nullable=True),
    sa.Column('tamamlandi', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefon'),
    sa.UniqueConstraint('token')
    )
    op.create_table('sektor_numaralar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=50), nullable=False),
    sa.Column('wa_no', sa.String(length=20), nullable=False),
    sa.Column('sektor', sa.String(length=50), nullable=False),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('sifre_hash', sa.String(length=256), nullable=False),
    sa.Column('sektor', sa.String(length=50), nullable=False),
    sa.Column('kredi', sa.Float(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.Column('son_islem', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefon')
    )
    op.create_table('islem_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('sektor', sa.String(length=50), nullable=True),
    sa.Column('islem_tipi', sa.String(length=50), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('kredi_kullanim', sa.Float(), nullable=True),
    sa.Column('detay', sa.JSON(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kredi_satin_alma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('paket_adi', sa.String(length=100), nullable=True),
    sa.Column('kredi_miktari', sa.Float(), nullable=True),
    sa.Column('tutar_tl', sa.Float(), nullable=True),
    sa.Column('odeme_durumu', sa.String(length=20), nullable=True),
    sa.Column('iyzico_token', sa.String(length=200), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kredi_satin_alma')
    op.drop_table('islem_log')
    op.drop_table('users')
    op.drop_table('sektor_numaralar')
    op.drop_table('kayit_bekleyen')
    # ### end Alembic commands ###
